-- 作者: Keiskei
-- 用途: 授予 cict 角色对 insur 补建表的全部权限
-- 基于: docs/insur_补表_创建脚本.sql 中定义的 25 张表

BEGIN;

GRANT USAGE ON SCHEMA insur TO cict;

GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.catalog_download_info TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.daily_reconcile_main TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.daily_reconcile_detail TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.ins_disease_type TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.ins_item_sh_unconflict TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.ins_reg_record TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.ins_standard_dept TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.ins_standard_dept_sh TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.ins_standard_dept_vs TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.ins_standard_dept_vs_sh TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.ins_system_mapping TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.month_check_info TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.month_check_fund_group TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.month_check_fee_info TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.month_check_solidify_info TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.psi_upload_rec TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.psi_sale_details TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.sel_fee_upload_info TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.settle_list_upload TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.sign_info TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.tcm_medicine_import TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.treat_item_import TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.insure_config TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.ins_log TO cict;
GRANT INSERT, TRIGGER, MAINTAIN, DELETE, UPDATE, REFERENCES, SELECT, TRUNCATE ON TABLE insur.wm_medicine_import TO cict;

GRANT USAGE ON SEQUENCE insur.ins_disease_type_id_seq TO cict;
GRANT USAGE ON SEQUENCE insur.ins_item_sh_unconflict_id_seq TO cict;
GRANT USAGE ON SEQUENCE insur.ins_system_mapping_id_seq TO cict;
GRANT USAGE ON SEQUENCE insur.month_check_solidify_info_id_seq TO cict;
GRANT USAGE ON SEQUENCE insur.psi_sale_details_id_seq TO cict;
GRANT USAGE ON SEQUENCE insur.sel_fee_upload_info_id_seq TO cict;
GRANT USAGE ON SEQUENCE insur.settle_list_upload_id_seq TO cict;
GRANT USAGE ON SEQUENCE insur.tcm_medicine_import_id_seq TO cict;
GRANT USAGE ON SEQUENCE insur.treat_item_import_id_seq TO cict;
GRANT USAGE ON SEQUENCE insur.wm_medicine_import_id_seq TO cict;

COMMIT;
